# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [
    "kvm-intel"
  ];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b539f07b-0eac-4e30-b400-33f701207859";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b539f07b-0eac-4e30-b400-33f701207859";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/.swapvol" = {
    device = "/dev/disk/by-uuid/b539f07b-0eac-4e30-b400-33f701207859";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/b539f07b-0eac-4e30-b400-33f701207859";
    fsType = "btrfs";
    options = ["subvol=persist"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6482-4BCE";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
