# pub keys
keys:
  - &users:
    - &tsunami age1
  - &hosts: # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &ishtar age1a2l4jfen25tlsjp58lh722r2x52zyflpx6yypncqr7rzlgzv05xsrqad88
    - &mokou age1

creation_rules:
  #path should be relative to location of this file (.sops.yaml)
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *tsunami
          - *ishtar
          - *mokou
