# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.disko.nixosModules.disko
  ];

  boot.loader.grub = {
    # no need to set devices, disko will add all devices that have a EF02 partition to the list already
    # devices = [ ];
    efiSupport = true;
    efiInstallAsRemovable = true;
  };
  boot.loader.timeout = 3;

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/431075cc-6f62-445b-b38a-a5362fcd83d5";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/889938f7-8be0-46a5-a8e5-384da3fb4f74";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  disko.devices = {
    disk = {
      sda = {
        type = "disk";
        device = "/dev/disk/by-uuid/431075cc-6f62-445b-b38a-a5362fcd83d5";
        content = {
          type = "gpt";
          partitions = {
            root = {
              type = "EF02";
              device = "/dev/disk/by-uuid/431075cc-6f62-445b-b38a-a5362fcd83d5";
              fsType = "ext4";
              mountpoint = "/";
            };
            swap = {
              type = "swap";
              mountOptions = ["noatime"];
              device = "/dev/disk/by-uuid/889938f7-8be0-46a5-a8e5-384da3fb4f74";
          };
        };
      };
    };
  };
}
